#!/bin/bash

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Symlink vim prefs
rm $HOME/.vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc

rm $HOME/.vim
ln -s $HOME/.dotfiles/shell/.vim $HOME/.vim

rm $HOME/.gitconfig
ln -s $HOME/.dotfiles/shell/.gitconfig $HOME/.gitconfig


#Setup for Pyenv
apt install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev

# Install curl
apt install curl -y

# Install wget
apt install wget -y

# Install git
apt install git -y

# Install vim
apt install vim -y

# Install Rgrep
apt install ripgrep -y

# Figlet Ascii art https://www.tecmint.com/create-ascii-text-banners-in-linux-terminal/
apt install figlet -y

#Install NVM for Nodejs
curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash

#Install zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# Install intelephense https://github.com/bmewburn/intelephense-docs
# For vim PHP intelephese
npm i intelephense -g

#Setup Mysql
apt install mysql-server -y
systemctl disable mysql

# Install Fzf
apt-get install fzf -y

# Install sublime
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
apt-get install apt-transport-https
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
apt update
apt install sublime-text

#Setup custom backgrounds with cron
read -p "Setup rotating backgrounds? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    # Create folder
    folder="${HOME}/Pictures/desktop-wallpapers"
    mkdir $folder

    # Get Images
    wget -P $folder https://cdn.osxdaily.com/wp-content/uploads/2020/12/macos-big-sur-updated-wallpapers-19.jpg
    wget -P $folder https://cdn.osxdaily.com/wp-content/uploads/2020/12/macos-big-sur-updated-wallpapers-24.jpg
    wget -P $folder https://cdn.osxdaily.com/wp-content/uploads/2020/12/macos-big-sur-updated-wallpapers-26.jpg
    wget -P $folder https://cdn.osxdaily.com/wp-content/uploads/2020/12/macos-big-sur-updated-wallpapers-27.jpg
    wget -P $folder https://cdn.osxdaily.com/wp-content/uploads/2020/12/macos-big-sur-updated-wallpapers-33.jpg
    wget -P $folder https://cdn.osxdaily.com/wp-content/uploads/2020/12/macos-big-sur-updated-wallpapers-32.jpg

    pic=$(ls $folder/* | shuf -n1)
    gsettings set org.gnome.desktop.background picture-options 'zoom'
    gsettings set org.gnome.desktop.background picture-uri "file://$pic"

    # Setup crontab
    crontab -l > cron_bkp
    echo "0 * * * * env DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus /$HOME/.dotfiles/scripts/change-wallpaper.sh" >> cron_bkp
    crontab cron_bkp
    echo "Crontab installed"
else
    echo "Custom rotating wallpapers not setup"
fi

# Setup terminal colors
echo 'Setting up terminal profiles'
echo '-----------------'

mkdir ~/.terminal
wget -O ~/.terminal/onehalfdark.sh https://raw.githubusercontent.com/sonph/onehalf/master/gnome-terminal/onehalfdark.sh
wget -O ~/.terminal/onehalflight.sh https://raw.githubusercontent.com/sonph/onehalf/master/gnome-terminal/onehalflight.sh

# Exit 0 is default for the script so to ensure we keep the script running after soruce we wish to return instead of exit
sed -i 's\exit 0\return\g' ~/.terminal/onehalfdark.sh
sed -i 's\exit 0\return\g' ~/.terminal/onehalflight.sh

source ~/.terminal/onehalfdark.sh
source ~/.terminal/onehalflight.sh

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo 'Things to do to make the one-half terminal theme work:'

echo '1. Go to your Terminal prefences and set your default theme (one half dark for same as VI theme)'
echo '2. Go to VIM and run :PlugInstall'

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
